name = "Prismatic Pantheon"
author = "KatTheFox"
version = "1.2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "43d9743a41e5d945d5b16de7abf55e74657c0220700e42c2ed6663b244cd120d"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.227"

[options]
acceptable-game-versions = ["1.21"]
