name = "Prismatic Pantheon"
author = "KatTheFox"
version = "1.2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3714e55732d55861768dea584c5517bee9aefe38b3aa17f784b8bb267bce7fb8"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.227"

[options]
acceptable-game-versions = ["1.21"]
