name = "Prismatic Pantheon"
author = "KatTheFox"
version = "1.2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3d9fc4af159ad0ef921312463f4849287fd7ea79770859deb32fe51dab7b50ca"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.227"

[options]
acceptable-game-versions = ["1.21"]
